### PR TITLE
Fix #2 - lost input_focus on tapping a spawner

### LINKED ISSUE #2: Tapping a spawner causes game to lose input_focus
## Expected behaviour

Tapping a spawner (invisible one) doesn't result in anything.

## Actual behaviour

`input_focus` is not returned so the slots remain unclickable.

Log output:

```
ERROR:SCRIPT: /emthree/emthree.lua:946: The receiver shouldn't be `nil`
stack traceback:
	[C]: in function 'post'
	/emthree/emthree.lua:946: in function </emthree/emthree.lua:919>
ERROR:SCRIPT: /emthree/emthree.lua:939: The receiver shouldn't be `nil`
stack traceback:
	[C]: in function 'post'
	/emthree/emthree.lua:939: in function </emthree/emthree.lua:919>
```

---

In my opinion, spawners are not supposed to be interactable - although @britzl, you never stated they should be. I'm considering a PR for this - it's very easy to fix anyway and better to keep it in upstream.

Thanks for the library, btw!

### PR DESCRIPTION
**Pull request by uncleNight**
Simply go out of on_input() if the tapped block is a spawner

### CODE REVIEW

File: emthree/emthree.lua [hunk 1]
```diff
@@ -923,6 +923,8 @@ function M.on_input(board, action)
 	local block = M.get_block(board, x, y)
 	if block and block.blocker then
 		return
+    elseif block and block.spawner then
```
Comment (britzl) [inline emthree/emthree.lua]: Could you please fix the indentation?

We could combine the two checks:

```
if block and (block.blocker or block.spawner) then
	return
end
```

**Review by britzl — CHANGES_REQUESTED** [review]

File: emthree/emthree.lua (hunk 1 above)
Comment (uncleNight) [reply emthree/emthree.lua]: Done, thanks! Editing it in `vim` wasn't the best idea :smile:

**Review by britzl — APPROVED** [review]
Thanks!
